services:
    datetime_normalizer:
        class: Symfony\Component\Serializer\Normalizer\DateTimeNormalizer
        tags: [serializer.normalizer]
        arguments:
            - { datetime_format: 'Y-m-d H:i:s' }

    get_set_method_normalizer:
        class: Symfony\Component\Serializer\Normalizer\GetSetMethodNormalizer
        tags: [serializer.normalizer]