services:
    datetime_normalizer:
        class: Symfony\Component\Serializer\Normalizer\DateTimeNormalizer
        tags: [serializer.normalizer]
        arguments:
            - { datetime_format: 'Y-m-d H:i:s' }

    get_set_method_normalizer:
        class: Symfony\Component\Serializer\Normalizer\GetSetMethodNormalizer
        tags: [serializer.normalizer]
        arguments:
            $classMetadataFactory: '@serializer.mapping.class_metadata_factory'
            $nameConverter: '@serializer.name_converter.metadata_aware'
            # Use property info to guess complex types (de)normalization
            $propertyTypeExtractor: '@property_info'
